name: 'Setup Knit'
description: 'Install zyedidia/knit'
  inputs:
  go-version:
    description: 'Go version'
    required: false
    default: 1.19.x
  knit-version:
    description: 'Knit version'
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - run: go install github.com/zyedidia/knit/cmd/knit@${{ inputs.knit-version }}
